name: Build Minecraft Mod

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Hier nutzen wir nun Java 17 passend zu Minecraft 1.20.4 und Gradle 8.7
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    private-setup-gradle:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

     Tar-Archiv erstellen und hochladen
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Fabric-Mod-Output
        path: build/libs/*.jar
